"""
Slot Architecture Engine for Addendum 3.
Deterministically resolves slot references, comparative direction tokens ({cmp:a,b}),
and valuation upside tokens ({cmp_upside:intrinsic,price}). Enforces the invariant that
all numerals and directional words are computed deterministically, never generated by the model.
"""

import re
import logging
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

@dataclass
class SlotContext:
    fields: dict[str, float | str | None] = field(default_factory=dict)

    def get_num(self, key: str) -> float | None:
        val = self.fields.get(key)
        if val is None:
            return None
        try:
            return float(val)
        except (ValueError, TypeError):
            return None

    def get_str(self, key: str) -> str:
        val = self.fields.get(key)
        return str(val) if val is not None else ""


def format_field_value(key: str, val: float | str | None) -> str:
    if val is None:
        return "N/A"
    if isinstance(val, str):
        return val

    num = float(val)
    key_lower = key.lower()

    if "price" in key_lower or "intrinsic" in key_lower or "target" in key_lower or "cap" in key_lower:
        return f"${num:,.2f}"
    if "pct" in key_lower or "margin" in key_lower or "roe" in key_lower or "growth" in key_lower or "wacc" in key_lower or "cagr" in key_lower or "yield" in key_lower:
        return f"{num:.1f}%"
    if "pe" in key_lower or "pb" in key_lower or "ps" in key_lower or "multiple" in key_lower or "ratio" in key_lower or "ev" in key_lower:
        return f"{num:.1f}x"

    if abs(num) >= 1000:
        return f"{num:,.1f}"
    if num == int(num):
        return f"{int(num)}"
    return f"{num:.2f}"


def eval_comparator(val_a: float | None, val_b: float | None, phrasing: str = "standard") -> str:
    """Deterministically evaluates direction between two values."""
    if val_a is None or val_b is None:
        return "compared to"

    diff = val_a - val_b
    ratio = val_a / val_b if val_b != 0 else 1.0

    if phrasing == "roe" or phrasing == "growth" or phrasing == "margin":
        if val_a > val_b * 1.15:
            return "substantially higher than"
        if val_a > val_b:
            return "higher than"
        if abs(val_a - val_b) <= 0.5:
            return "in line with"
        if val_a < val_b * 0.85:
            return "substantially lower than"
        return "lower than"

    # Standard multiple / price comparator
    if ratio >= 1.25:
        return "well above"
    if ratio > 1.03:
        return "above"
    if 0.97 <= ratio <= 1.03:
        return "in line with"
    if ratio >= 0.75:
        return "below"
    return "well under"


def eval_upside_direction(intrinsic: float | None, price: float | None) -> str:
    """NARR-01 & NARR-02: Deterministically evaluates upside vs downside to intrinsic value."""
    if intrinsic is None or price is None or price <= 0:
        return "fair value assessment"

    upside_pct = ((intrinsic - price) / price) * 100.0
    if upside_pct >= 0:
        return f"an upside of {upside_pct:.1f}% to intrinsic value"
    return f"a downside of {abs(upside_pct):.1f}% to intrinsic value"


def filter_banned_connectives(text: str) -> str:
    """Part C: Deterministic post-filter removing conclusion-restating filler connectives."""
    banned = [
        r"\breinforcing\s+the\s+valuation\s+gap\b",
        r"\breinforcing\s+confidence\b",
        r"\bunderscoring\s+the\s+thesis\b",
        r"\bfurther\s+supports\s+the\s+call\b",
        r"\bhighlighting\s+resilience\b",
    ]
    out = text
    for pat in banned:
        out = re.sub(pat, "", out, flags=re.I)
    # Clean up double spaces
    out = re.sub(r"\s+", " ", out).strip()
    return out


def resolve_slots(template_text: str, context: SlotContext) -> str:
    """
    Substitutes slot tokens:
      - {key.name} -> formatted numeric/string value
      - {cmp:keyA,keyB} -> deterministic direction phrase ("well above", "below", etc.)
      - {cmp_upside:intrinsic,price} -> deterministic upside/downside phrase
    """
    if not template_text:
        return ""

    text = template_text

    # 1. Resolve {cmp_upside:keyA,keyB}
    def _sub_upside(m):
        k1, k2 = m.group(1).strip(), m.group(2).strip()
        v1, v2 = context.get_num(k1), context.get_num(k2)
        return eval_upside_direction(v1, v2)

    text = re.sub(r"\{cmp_upside:([^,}]+),([^}]+)\}", _sub_upside, text)

    # 2. Resolve {cmp:keyA,keyB} or {cmp:keyA,keyB,phrasing}
    def _sub_cmp(m):
        parts = [p.strip() for p in m.group(1).split(",")]
        if len(parts) >= 2:
            k1, k2 = parts[0], parts[1]
            phrasing = parts[2] if len(parts) >= 3 else "standard"
            v1, v2 = context.get_num(k1), context.get_num(k2)
            return eval_comparator(v1, v2, phrasing)
        return "compared to"

    text = re.sub(r"\{cmp:([^}]+)\}", _sub_cmp, text)

    # 3. Resolve field slots {key.name}
    def _sub_field(m):
        key = m.group(1).strip()
        val = context.fields.get(key)
        return format_field_value(key, val)

    text = re.sub(r"\{([a-zA-Z0-9_\.]+)\}", _sub_field, text)

    # 4. Filter banned connectives
    text = filter_banned_connectives(text)

    return text
